# Generated by Django 6.0.3 on 2026-05-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='tipo',
            field=models.CharField(choices=[('vale-lanche', 'Vale-Lanche'), ('vale-bebida', 'Vale-Bebida'), ('pix', 'PIX')], max_length=20),
        ),
    ]
